### ISSUE TITLE
Idea: scripting

### ISSUE THREAD

**Issue by Astatin3** [toccatina/altoclef#87]
## Scripting concept
what if you impemented scripts? it would be pretty cool for automation, also  this would replace any kind of custom baritone scripting because this fork would be so much easier to use

Files could be placed in a folder in MC directory called "Altoclef_scrips"
Code concept (using the pre-existing commands+vars):

`'name' = 'netherite'
'description' = 'a bot that gets netherite armor and puts it in a chest'
'loop' = true

code {
     var [home] = <choords>
    <get {'netherite_helmet', 'netherite_chestplate', 'netherite_leggings', 'netherite_boots'}>
    <get 'chest'>
     <goto [home]>
     var [chest] = <place 'chest'> 
     }`

keys i used for example:
vars:  [ ]
run alto command: < >
array/function: { }

or you could do somthing as simple as multiple commands in one line:

`@goto nether, @goto 123 123 123, @follow Player123`

**BE WARED:**
I know nothing about java programing so i don't know how hard this would be to implement

**Comment by adrisj7** [comment]
A scripting language would be dope, but it would be a massive undertaking. This project has a few directions it can go in, and scripting is up there among the top 3 I'd say. I'll close this suggestion though since it's a pretty tall order, just keep in mind that I'm totally looking forward to implementing something like this in the future :)
